// GENERATED by scripts/gen-ops.ts - DO NOT EDIT. Run `just gen`.
//
// The bridge's identity constants. PINNED_EXTENSION_ID is DERIVED from
// extension/manifest.json's `key` (Chrome's own id derivation), so it cannot
// drift from the manifest; NATIVE_HOST_ID comes from contracts/identity.json.
// scripts/check-extension-id.ts verifies the installers and the Rust host
// against the same sources.

// The extension ID Chrome derives from the manifest `key`. The native-
// messaging host manifest pins this in `allowed_origins`, so a build without
// the pinned key is rejected by the host.
export const PINNED_EXTENSION_ID = "mkjjlmjbcljpcfkfadfmhblmmddkdihf";

// The native-messaging host id: what the extension passes to connectNative,
// what the Rust host expects, and the host manifest's name/filename stem.
export const NATIVE_HOST_ID = "com.vivswan.chromium_bridge.host";
